### ISSUE TITLE
Make sure one can run XML config examples

### ISSUE THREAD

**Issue by Nyholm** [symfony-tools/code-block-checker#17]
XML is currently [disabled](https://github.com/symfony-docs-tools/code-block-checker/blob/886c6ad47df563c62944d8dd5e5c1043ac630293/src/Service/CodeNodeRunner.php#L74). I got errors on every code block when testing. It is probably me missing something, because I don't think every XML code block is wrong.

**Comment by Nyholm** [comment]
I dont know much about XML config.. but I cannot get it to work at all. 

https://github.com/symfony-docs-tools/symfony-application/pull/3

**Comment by HeahDude** [comment]
Maybe https://github.com/symfony/symfony/pull/46594 can partially fix this?

**Comment by HeahDude** [comment]
https://github.com/symfony/symfony/pull/46594 has been merged.
Friendly ping @Nyholm :), anything else needed here to fix the XML config?

**Comment by Nyholm** [comment]
Thank you. 

What happens if you enable the xml and run the test on all existing docs locally?

**Comment by OskarStark** [comment]
What about tagging a new major of the tool and create a PR on symfony/docs with the new release?

**Comment by HeahDude** [comment]
>What happens if you enable the xml and run the test on all existing docs locally?

In any case I may try this tonight, thanks.

**Comment by HeahDude** [comment]
It seems that the tools cannot run on 4.4 is that expected?

**Comment by HeahDude** [comment]
I think we need a branch of this tool dedicated for each major version of Symfony.
